# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    app.form.registration:
        class: AppBundle\Form\Type\ImieType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.handler.registration:
        class: AppBundle\Form\type\dodaj
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false